import matplotlib.pyplot as plt 

def to_int(inp):
    '''
    This function is built to take the tuples read in from a file of most common words
    and turn them into integers that can be processed by pyplot
    '''
    # print inp, type(inp)
    return int(inp[0]), int(inp[1])

def plot_frequency():
    '''
    This function reads in a file of most common words generated by the sort_dict function
    and converts them into a list of tuples of integers, then plots that data.
    The plot is frequency vs. order of how common
    '''
    data = [to_int(tuple(line.strip().split(' ',1))) for line in open ('./plotable1001')]
    print data
    plt.plot(*zip(*data))
    plt.show()
# plot_frequency()


def strip_common():
    '''
    This function strips 127 common words, often found in NLTKs, out a list of common words and prints the 
    50 most common remaining words
    '''
    with open('./1000onlywords') as f:
        data = f.read().splitlines()
        common = ['all', 'just', 'being', 'over', 'both', 'through', 'yourselves', 'its', 'before', 'herself', 'had', 'should', 'to', 'only', 'under', 'ours', 'has', 'do', 'them', 'his', 'very', 'they', 'not', 'during', 'now', 'him', 'nor', 'did', 'this', 'she', 'each', 'further', 'where', 'few', 'because', 'doing', 'some', 'are', 'our', 'ourselves', 'out', 'what', 'for', 'while', 'does', 'above', 'between', 't', 'be', 'we', 'who', 'were', 'here', 'hers', 'by', 'on', 'about', 'of', 'against', 's', 'or', 'own', 'into', 'yourself', 'down', 'your', 'from', 'her', 'their', 'there', 'been', 'whom', 'too', 'themselves', 'was', 'until', 'more', 'himself', 'that', 'but', 'don', 'with', 'than', 'those', 'he', 'me', 'myself', 'these', 'up', 'will', 'below', 'can', 'theirs', 'my', 'and', 'then', 'is', 'am', 'it', 'an', 'as', 'itself', 'at', 'have', 'in', 'any', 'if', 'again', 'no', 'when', 'same', 'how', 'other', 'which', 'you', 'after', 'most', 'such', 'why', 'a', 'off', 'i', 'yours', 'so', 'the', 'having', 'once']
        s = set(common)
        cleandata = [x for x in data if x not in s]
        for i in range(50):
            print cleandata[i] + ', '
strip_common()
